### ISSUE TITLE
Tests fail on v0.5

### ISSUE THREAD

**Issue by ranjanan** [JuliaStats/Distributions.jl#538] opened 2016-09-20 18:09 UTC
On Mac, with the Julia 0.5 release, I got the following error:
```
ERROR: LoadError: On worker 4:
LoadError: can only precompile from node 1
 in compilecache at ./loading.jl:560
 in require at ./loading.jl:393
 in jlcall_require_22337 at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include_string at ./loading.jl:441
 in jlcall_include_string_30821 at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include_from_node1 at ./loading.jl:491
 in jlcall_include_from_node1_20125 at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in #5 at /Users/ranjan/.julia/v0.5/Distributions/test/runtests.jl:44
 in #625 at ./multi.jl:1421
 in run_work_thunk at ./multi.jl:1001
 in macro expansion at ./multi.jl:1421 [inlined]
 in #624 at ./event.jl:68
while loading /Users/ranjan/.julia/v0.5/Distributions/test/continuous.jl, in expression starting on line 5
 in #remotecall_fetch#606(::Array{Any,1}, ::Function, ::Function, ::Base.Worker, ::String, ::Vararg{String,N}) at ./multi.jl:1070
 in remotecall_fetch(::Function, ::Base.Worker, ::String, ::Vararg{String,N}) at ./multi.jl:1062
 in #remotecall_fetch#609(::Array{Any,1}, ::Function, ::Function, ::Int64, ::String, ::Vararg{String,N}) at ./multi.jl:1080
 in remotecall_fetch(::Function, ::Int64, ::String, ::Vararg{Any,N}) at ./multi.jl:1080
 in #remotecall_pool#689(::Array{Any,1}, ::Function, ::Function, ::Function, ::WorkerPool, ::String, ::Vararg{String,N}) at ./workerpool.jl:93
 in remotecall_pool(::Function, ::Function, ::WorkerPool, ::String, ::Vararg{String,N}) at ./workerpool.jl:91
 in #remotecall_fetch#692(::Array{Any,1}, ::Function, ::Function, ::WorkerPool, ::String, ::Vararg{String,N}) at ./workerpool.jl:124
 in remotecall_fetch(::Function, ::WorkerPool, ::String, ::Vararg{String,N}) at ./workerpool.jl:124
 in (::Base.###697#698#700{WorkerPool,##5#6})(::Array{Any,1}, ::Function, ::String, ::Vararg{String,N}) at ./workerpool.jl:151
 in (::Base.##697#699)(::String, ::Vararg{String,N}) at ./workerpool.jl:151
 in macro expansion at ./asyncmap.jl:63 [inlined]
 in (::Base.##755#757{Base.AsyncCollector,Base.AsyncCollectorState})() at ./task.jl:360
 in sync_end() at ./task.jl:311
 in done(::Base.AsyncCollector, ::Base.AsyncCollectorState) at ./asyncmap.jl:124
 in pump_source(::Base.AsyncGenerator, ::Base.AsyncGeneratorState) at ./asyncmap.jl:185
 in next(::Base.AsyncGenerator, ::Base.AsyncGeneratorState) at ./asyncmap.jl:201
 in _collect(::UnitRange{Int64}, ::Base.AsyncGenerator, ::Base.HasEltype, ::Base.SizeUnknown) at ./array.jl:282
 in #pmap#714(::Bool, ::Int64, ::Void, ::Int64, ::Float64, ::Function, ::Void, ::Void, ::Void, ::Base.#pmap, ::WorkerPool, ::##5#6, ::Array{String,1}) at ./pmap.jl:121
 in pmap(::WorkerPool, ::Function, ::Array{String,1}) at ./pmap.jl:80
 in #pmap#726(::Array{Any,1}, ::Function, ::Function, ::Array{String,1}) at ./pmap.jl:146
 in pmap(::Function, ::Array{String,1}) at ./pmap.jl:146
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/ranjan/.julia/v0.5/Distributions/test/runtests.jl, in expression starting on line 43
```
versioninfo()
```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```
I've saved the entire failure gist [here](https://gist.github.com/ranjanan/8de31db177d043dac955ca269a2a780c)

**Comment by ararslan** [comment] 2016-09-20 18:22
What were you doing that gave you the error? Was it just `Pkg.test("Distributions")`? It appears so based on the Gist, just wanted to make sure.

> `LoadError: can only precompile from node 1`

What happens if you do this:
```julia
Pkg.update()
using Distributions, JSON, ForwardDiff
Pkg.test("Distributions")
```
?

I'm wondering if maybe precompiling it first, *then* running the tests (which use parallelism because otherwise they take ages) would make a difference.

**Comment by jmxpearson** [comment] 2016-09-20 18:25
I can reproduce.

The line that errors is

`using Calculus.derivative`

and doing `using Calculus` at the REPL gives me

```julia
julia> using Calculus
INFO: Precompiling module Calculus.
WARNING: Module Compat with uuid 52284743989391 is missing from the cache.
This may mean module Compat does not support precompilation but is imported by a module that does.
ERROR: LoadError: Declaring __precompile__(false) is not allowed in files that are being precompiled.
 in require(::Symbol) at ./loading.jl:385
 in require(::Symbol) at /Users/jmxp/code/julia/usr/lib/julia/sys.dylib:?
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Users/jmxp/code/julia/usr/lib/julia/sys.dylib:?
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Users/jmxp/code/julia/usr/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
 in _start() at /Users/jmxp/code/julia/usr/lib/julia/sys.dylib:?
while loading /Users/jmxp/.julia/v0.5/Calculus/src/Calculus.jl, in expression starting on line 4
ERROR: Failed to precompile Calculus to /Users/jmxp/.julia/lib/v0.5/Calculus.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:422
 in require(::Symbol) at /Users/jmxp/code/julia/usr/lib/julia/sys.dylib:?
```

**Comment by ararslan** [comment] 2016-09-20 18:36
Hm, did `__precompile__` get moved from Base to Core or something in 0.5? Calculus.jl is only precompiling if `isdefined(Base, :__precompile__)`.

**Comment by jmxpearson** [comment] 2016-09-20 19:35
```julia
julia> isdefined(Base, :__precompile__)
true
```

But after running `Base.compilecache` on Compat and Calculus, I can now do `using Calculus`. The test failure still persists.

**Comment by jmxpearson** [comment] 2016-09-20 19:42
Okay, I endedu up recompiling:
- Calculus
- JSON
- ForwardDiff

Note that the last two are only in `test/REQUIRE` and so might not be automatically be recompiled when `using Distributions`???

Tests now pass on my machine:

```julia
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by ararslan** [comment] 2016-09-20 19:49
If I'm not mistaken, I think the test dependencies are only compiled when running `Pkg.test`.

I wonder if this could be fixed by putting `using Distributions, JSON, ForwardDiff` at the top of test/runtests.jl, before things are split between parallel workers? That should ensure they're compiled when they're called.

**Comment by jmxpearson** [comment] 2016-09-20 20:17
I ran `Pkg.test` initially to produce the failure, so I'm not sure that's correct.

I'd be interested to know whether this happens on a fresh install, or if it results from some unhandled staleness in the package directories post-upgrade.

**Comment by andreasnoack** [comment] 2016-09-20 20:26
We'll need to `using` the packages in `runtests` before the `pmap`. Right now some of the packages are only loaded inside the individual test files.

**Comment by ararslan** [comment] 2016-09-20 22:33
Looks like some of the packages being used in the tests aren't declared in test/REQUIRE. Should definitely fix that, if nothing else. PR incoming shortly...

**Closed** 2016-09-22 12:07 UTC
