### ISSUE TITLE
Use keyword arguments for distribution parameters

### ISSUE THREAD

**Issue by jariji** [JuliaStats/Distributions.jl#1661] opened 2023-01-16 20:26 UTC
`Exponential(x)` is unclear without reading the docs: `x` could be the rate or its inverse, the scale. It would be less error-prone if keyword arguments were used, such as `Exponential(scale=x)`.

**Comment by devmotion** [comment] 2023-01-16 20:32
I'll close this is a duplicate of https://github.com/JuliaStats/Distributions.jl/issues/768. There was also an attempt at it in #823 (unfortunately did not receive many comments and I should update it).

**Closed by devmotion** 2023-01-16 20:32 UTC
