### ISSUE TITLE
`support` gives error on infinite discrete distributions

### ISSUE THREAD

**Issue by mauricelanghinrichs** [JuliaStats/Distributions.jl#1919] opened 2024-11-29 09:38 UTC
I noticed that the `support` method on the following (maybe more) discrete distributions (countable infinite) cannot be evaluated. Instead an `InexactError: Int64(Inf)` occurs:

```julia
support(Geometric(0.5)) # ERROR
support(Poisson(4)) # ERROR
support(NegativeBinomial(4, 0.5)) # ERROR
```

While in constrast the following is as expected

```julia
support(Binomial(10, 0.5)) # 0:10
```

Full error for first case:
```julia
julia> support(Geometric(0.5))
ERROR: InexactError: Int64(Inf)
Stacktrace:
 [1] Int64
   @ ./float.jl:994 [inlined]
 [2] convert
   @ ./number.jl:7 [inlined]
 [3] _round_convert
   @ ./rounding.jl:480 [inlined]
 [4] round
   @ ./rounding.jl:479 [inlined]
 [5] round(::Type{Int64}, x::Float64)
   @ Base ./rounding.jl:477
 [6] support(d::Geometric{Float64})
   @ Distributions ~/.julia/packages/Distributions/Qeo2J/src/univariates.jl:112
 [7] top-level scope
   @ REPL[2]:1
```

Versions:
```julia
julia> versioninfo()
Julia Version 1.11.1
Commit 8f5b7ca12ad (2024-10-16 10:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (x86_64-apple-darwin22.4.0)
  CPU: 20 × Intel(R) Core(TM) i9-10910 CPU @ 3.60GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, skylake)
Threads: 20 default, 0 interactive, 10 GC (on 20 virtual cores)
Environment:
  JULIA_EDITOR = code
```

and `Distributions v0.25.113`.

**Comment by devmotion** [comment] 2024-11-29 09:41
It seems this is a duplicate of https://github.com/JuliaStats/Distributions.jl/issues/1254

**Closed by devmotion** 2024-11-29 09:41 UTC

**Comment by mauricelanghinrichs** [comment] 2024-11-29 09:42
yes, sorry did not see that although I searched (briefly). thanks!
