### ISSUE TITLE
Unable to sample from VonMisesFisher

### ISSUE THREAD

**Issue by nishadgothoskar** [JuliaStats/Distributions.jl#1464] opened 2021-12-27 21:20 UTC
I'm encountering issues when sampling from a VonMisesFischer centered on the identity orientation.
```
julia> rand(Distributions.VonMisesFisher([1.0, 0.0, 0.0, 0.0], 100.0))
4-element Vector{Float64}:
 NaN
 NaN
 NaN
 NaN
```
Digging deeper, I found the issue is here:
```
julia> s = Distributions.sampler(Distributions.VonMisesFisher([1.0, 0.0, 0.0, 0.0], 100.0))
Distributions.VonMisesFisherSampler(4, 100.0, 0.007499578172454263, 0.9851124936725868, 87.9465773626279, [NaN, NaN, NaN, NaN])
```
where the NaN vector is output by this function:
https://github.com/JuliaStats/Distributions.jl/blob/d6985ad5f08990123b9ba84431626f22f1a408bd/src/samplers/vonmisesfisher.jl#L87

Any help here would be appreciated!

(Unrelated issue related to VMF is the following, where it should be `abs(norm(v) - 1.0) < 1.0e-12`
https://github.com/JuliaStats/Distributions.jl/blob/b4ce282f50084bdd0772b7d856caf574f7cc4da4/src/utils.jl#L14

**Comment by devmotion** [comment] 2021-12-27 21:58
Thanks for the issue. It seems to be a duplicate of https://github.com/JuliaStats/Distributions.jl/issues/1423.

**Closed** 2021-12-27 21:59 UTC
