### ISSUE TITLE
Add log-uniform distribution?

### ISSUE THREAD

**Issue by oschulz** [JuliaStats/Distributions.jl#1417] opened 2021-11-08 16:00 UTC
We currently have a [log-uniform/reciprocal distribution](https://en.wikipedia.org/wiki/Reciprocal_distribution) in BAT.jl (https://github.com/bat/BAT.jl/blob/master/src/distributions/log_uniform.jl). It was requested for a project, but should be quite useful in general. Maybe it would make sense to move it to Distributions?

CC @devmotion

**Comment by devmotion** [comment] 2021-11-08 20:46
Yes, I think it would make sense.

There's already an issue (https://github.com/JuliaStats/Distributions.jl/issues/1315) and a PR (https://github.com/JuliaStats/Distributions.jl/pull/1349).

I'll close this as a duplicate of https://github.com/JuliaStats/Distributions.jl/issues/1315. I think it would be great though if we could merge potential improvements of your implementation in BAT in the PR, so feel free to comment there and suggest changes.

**Closed by devmotion** 2021-11-08 20:46 UTC

**Comment by oschulz** [comment] 2021-11-08 21:05
Will do!
