### ISSUE TITLE
fail to calculate quantile

### ISSUE THREAD

**Issue by 1991jhf** [JuliaStats/Distributions.jl#1567] opened 2022-06-21 09:06 UTC
Here is an failed case

```
using Distributions
quantile(Gamma{Float64}(0.0030345129757232197, 4.55039055313028), 0.106)
```

ERROR: DomainError with -5.50108e-319:
log will only return a complex result if called with a complex argument. Try log(Complex(x)).

**Comment by devmotion** [comment] 2022-06-21 09:15
I assume this is caused by the same problem in SpecialFunctions as https://github.com/JuliaMath/SpecialFunctions.jl/issues/403.

**Comment by devmotion** [comment] 2022-06-23 09:19
The example would be fixed by https://github.com/JuliaMath/SpecialFunctions.jl/pull/404.

**Closed** 2022-07-05 08:59 UTC
