### ISSUE TITLE
Can not sample from Von Mises

### ISSUE THREAD

**Issue by mbeltagy** [JuliaStats/Distributions.jl#579] opened 2017-03-07 08:07 UTC
```julia
julia> v=VonMises(30,2)
Distributions.VonMises{Float64}(μ=30.0, κ=2.0)

julia> rand(v)
ERROR: MethodError: no method matching quantile(::Distributions.VonMises{Float64}, ::Float64)
Closest candidates are:
  quantile(::Distributions.Distribution{Distributions.Univariate,S<:Distributions.ValueSupport}, ::Real) at /home/elbeltagy/.julia/Distributions/src/univariates.jl:163
  quantile(::Distributions.DiscreteUniform, ::Float64) at /home/elbeltagy/.julia/Distributions/src/univariate/discrete/discreteuniform.jl:114
  quantile(::Distributions.EmpiricalUnivariateDistribution, ::Float64) at /home/elbeltagy/.julia/Distributions/src/empirical.jl:61
  ...
 in rand(::Distributions.VonMises{Float64}) at /home/elbeltagy/.julia/Distributions/src/univariates.jl:64

```

**Comment by matbesancon** [comment] 2018-09-19 15:14
It comes from the fact that the CDF does not have an analytical expression. I wonder if we should not move all such distributions to another package and then offer different routines to find a given quantile.

The other solution is to implement a simple search, I might do that in the mean time

**Comment by matbesancon** [comment] 2018-09-19 15:34
Requires #320 to be merged first

**Comment by yha** [comment] 2019-01-28 00:06
This is not due to a missing CDF implementation:
```
julia> v = VonMises(0,1)
VonMises{Float64}(μ=0.0, κ=1.0)

julia> rand(v,1)
1-element Array{Float64,1}:
 1.8643641705208138

julia> rand(v)
ERROR: MethodError: no method matching iterate(::VonMises{Float64})
[...]
```
The problem is that `rand(::UnivariateDistribution,dims...)` uses `sampler(v)`, whereas `rand(::UnivariateDistribution)` bypasses the sampler completely.
This could be fixed by `rand(v::VonMises) = rand(sampler(v))`, but I'm not sure that's the best fix. Shouldn't the generic `rand(d::UnivariateDistribution)` refer to the sampler? It could, for example, call `_rand(sampler(d))`, with the generic `_rand` implementing the current fallback of using the cdf (currently there `_rand!` and no `_rand`).

**Closed** 2019-05-16 10:45 UTC
