### ISSUE TITLE
What's missing for 1.0?

### ISSUE THREAD

**Issue by Datseris** [JuliaStats/Distributions.jl#1239] opened 2020-12-14 23:54 UTC
Hi there, 
this awesome package has been around for a really long time and is a dependency of many Julia packages but still not in 1.0. From my experience, the interface has also been "stable" for a quite a while.

What is missing? What breaking changes are planned that keep this package obtaining its first stable version? Do you have a list of these somewhere? If not, can you please state them here, or somewhere else, to give the developers that use this package an idea?

**Comment by matbesancon** [comment] 2020-12-16 17:52
@JuliaRegistrator register()

**Comment by Datseris** [comment] 2020-12-16 18:34
@matbesancon I'm not sure whether I should be able to deduce something here, but I can't.

**Comment by matbesancon** [comment] 2020-12-16 18:48
@Datseris sorry no I just used the issue opened to register a version

**Comment by Datseris** [comment] 2020-12-16 21:56
Oh okay. BTW you can also tag releases by commenting on commits. I typically find this cleaner on the long term, as the comment that tags the release is directly associated the commit this release should be done on.

**Comment by fedario** [comment] 2021-01-01 20:11
Regarding the original question:
I believe this package needs more documentation.

For example, I was trying to figure out if I can backpropagate through rand with respect to the distribution parameters in Flux. That is relevant for things like variational inference. After working my way through the code I'm pretty convinced that this is possible, at least for the multivariate normal distribution.

Are there plans to improve the documentation and if so, how could I help?

**Comment by matbesancon** [comment] 2021-01-02 13:52
I will close this issue as a duplicate of https://github.com/JuliaStats/Distributions.jl/issues/880

>  I believe this package needs more documentation.

Completely agreed, more and better.

> For example, I was trying to figure out if I can backpropagate through rand with respect to the distribution parameters in Flux

Through other functions yes, but through rand I am not sure this is doable? `rand` is not even a function in the mathematical sense, or if you consider `rand(rng, d)`, it is mutating its first argument in a non-differentiable way

**Comment by matbesancon** [comment] 2021-01-02 13:53
> Are there plans to improve the documentation and if so, how could I help?

No plans yet, but whenever you see things that could be improved a PR is useful

**Closed** 2021-01-02 13:53 UTC

**Comment by fedario** [comment] 2021-01-02 16:08
> Through other functions yes, but through rand I am not sure this is doable? `rand` is not even a function in the mathematical sense, or if you consider `rand(rng, d)`, it is mutating its first argument in a non-differentiable way

Good point! What I was trying to do with this package is called the [reparameterization trick](https://stats.stackexchange.com/questions/199605/how-does-the-reparameterization-trick-for-vaes-work-and-why-is-it-important).

In case of the MvNormal distribution that seems to be possible, however, my problem was that there is nothing like a batch dimension for distribution along the line of [PyTorch's distributions](https://pytorch.org/docs/stable/distributions.html). This made it impossible to create a batch of MvNormal distributions by passing a 2d array, which is necessary for CUDA arrays, since they discourage scalar access.
