### ISSUE TITLE
`pdf` on an array of values is ambiguous

### ISSUE THREAD

**Issue by yuvalwas** [JuliaStats/Distributions.jl#1528] opened 2022-04-03 16:25 UTC
Hi,
forgive me I this was already discussed, I tried to look in the issues.
```
julia> pdf(Normal(), 0:0.1:1)
ERROR: MethodError: pdf(::Normal{Float64}, ::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}) is ambiguous. Candidates:
  pdf(d::Distribution{ArrayLikeVariate{N}}, x::AbstractArray{<:Real, M}) where {N, M} in Distributions at /home/yuval/.julia/packages/Distributions/Glk9C/src/common.jl:251
  pdf(d::UnivariateDistribution, X::AbstractArray) in Distributions at deprecated.jl:70
Possible fix, define
  pdf(::UnivariateDistribution, ::AbstractArray{T, M} where T<:Real) where M
```
It is not for me to say whether `pdf` on arrays should be deprecated or not, as I am probably not aware of all the considerations around it, but at the moment it seems to be both. The reason I didn't use `pdf.(Normal(), 0:0.1:1)` is because I actually hoped to do `pdf.(Normal.(1:3), 0:0.1:1)` and get an 11X3 matrix. Thus personally I would prefer it not deprecated. Is there something better than `[pdf(Normal(u) ,x) for x in 0:0.1:1, u in 1:3]`?
Thanks

**Comment by sethaxen** [comment] 2022-04-03 16:44
> The reason I didn't use `pdf.(Normal(), 0:0.1:1)` is because I actually hoped to do `pdf.(Normal.(1:3), 0:0.1:1)` and get an 11X3 matrix. Thus personally I would prefer it not deprecated. Is there something better than `[pdf(Normal(u) ,x) for x in 0:0.1:1, u in 1:3]`?

There is!

```julia
julia> pdf.(Normal.((1:3)'), 0:0.1:1)
11×3 Matrix{Float64}:
 0.241971  0.053991   0.00443185
 0.266085  0.0656158  0.00595253
 0.289692  0.0789502  0.00791545
 0.312254  0.0940491  0.0104209
 0.333225  0.110921   0.013583
 0.352065  0.129518   0.0175283
 0.36827   0.149727   0.0223945
 0.381388  0.171369   0.028327
 0.391043  0.194186   0.0354746
 0.396953  0.217852   0.0439836
 0.398942  0.241971   0.053991
```

**Comment by devmotion** [comment] 2022-04-03 20:37
I'll close this issue since it is a duplicate of https://github.com/JuliaStats/Distributions.jl/issues/1463.

**Closed** 2022-04-03 20:37 UTC
