### ISSUE TITLE
Cauchy Float32 does not  honor the element type of distribution

### ISSUE THREAD

**Issue by josemanuel22** [JuliaStats/Distributions.jl#1757] opened 2023-08-03 15:52 UTC
I have encountered the following problem described in #1071 with cauchy distribution.
```
Cauchy(1.0f0, 2.0f0)
Cauchy{Float32}(μ=1.0f0, σ=2.0f0)
```
```
julia>  eltype(rand(Cauchy(1.0f0, 2.0f0)))
Float64
``` 

Julia Version `1.9.0`
Distributions `v0.25.98`

**Comment by devmotion** [comment] 2023-08-03 18:44
I close this as duplicate of #1071. As described in this issue, this behaviour is intentional and the current design of Distributions.

**Closed by devmotion** 2023-08-03 18:45 UTC
