### ISSUE TITLE
Passing random generator to rand functions

### ISSUE THREAD

**Issue by KrisDM** [JuliaStats/Distributions.jl#452] opened 2016-01-26 16:21 UTC
Is there a possibility to pass a random generator to the rand functions other than the default one? My use case is massively parallel Monte Carlo, and the Mersenne Twister is considered to be sub-optimal for that.

**Comment by simonbyrne** [comment] 2016-01-26 16:42
Not yet.

duplicate of #436.

**Closed by simonbyrne** 2016-01-26 16:42 UTC
