### ISSUE TITLE
Error on sampling from truncated MixtureModel

### ISSUE THREAD

**Issue by axsk** [JuliaStats/Distributions.jl#1102] opened 2020-04-20 08:18 UTC
Trying to sample from a Truncated MixtureModel throws an error.

```
julia> rand(truncated(MixtureModel([Normal(0,1)]), 0, 1))
ERROR: MethodError: no method matching iterate(::MixtureModel{Univariate,Continuous,Normal{Float64},Float64})
Closest candidates are:
  iterate(::Core.SimpleVector) at essentials.jl:600
  iterate(::Core.SimpleVector, ::Any) at essentials.jl:600
  iterate(::ExponentialBackOff) at error.jl:218
  ...
Stacktrace:
 [1] copyto!(::Array{Float64,1}, ::MixtureModel{Univariate,Continuous,Normal{Float64},Float64}) at ./abstractarray.jl:722
 [2] _collect(::UnitRange{Int64}, ::MixtureModel{Univariate,Continuous,Normal{Float64},Float64}, ::Base.HasEltype, ::Base.HasLength) at ./array.jl:566
 [3] collect(::MixtureModel{Univariate,Continuous,Normal{Float64},Float64}) at ./array.jl:560
 [4] #quantile#53(::Bool, ::typeof(quantile), ::MixtureModel{Univariate,Continuous,Normal{Float64},Float64}, ::Float64) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Statistics/src/Statistics.jl:966
 [5] quantile(::MixtureModel{Univariate,Continuous,Normal{Float64},Float64}, ::Float64) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Statistics/src/Statistics.jl:966
 [6] quantile(::Truncated{MixtureModel{Univariate,Continuous,Normal{Float64},Float64},Continuous,Float64}, ::Float64) at /Users/alex/.julia/packages/Distributions/dTXqn/src/truncate.jl:92
 [7] rand(::Random._GLOBAL_RNG, ::Truncated{MixtureModel{Univariate,Continuous,Normal{Float64},Float64},Continuous,Float64}) at /Users/alex/.julia/packages/Distributions/dTXqn/src/univariates.jl:175
 [8] rand(::Truncated{MixtureModel{Univariate,Continuous,Normal{Float64},Float64},Continuous,Float64}) at /Users/alex/.julia/packages/Distributions/dTXqn/src/genericrand.jl:22
 [9] top-level scope at REPL[9]:1
```

It worked years ago (trying to reproduce some old result and now I'm stuck here).

Any ideas what's going on here?
I'm on Julia 1.3.1, Distributions v0.23.2

**Comment by nignatiadis** [comment] 2020-11-03 10:18
This is a duplicate of https://github.com/JuliaStats/Distributions.jl/issues/1039.

**Closed** 2021-09-02 09:34 UTC
