### ISSUE TITLE
[`InverseGaussian`?] `quantile()` hangs for larger number of `σ`'s (`quantile_newton` not converging)

### ISSUE THREAD

**Issue by LebedevRI** [JuliaStats/Distributions.jl#1898] opened 2024-09-11 22:04 UTC
I'm not sure if this is specific to this distribution, but this seems really problematic.

```julia
using Distributions
using SpecialFunctions

p(num_σ) = erf(num_σ/sqrt(2))

d = InverseGaussian{Float64}(1.187997687788096, 60.467382225458564)

@show d
@time @show quantile(d, p(4)) # near-instant
@time @show quantile(d, p(5)) # hangs, 10++ seconds
```
```
julia> versioninfo()
Julia Version 1.10.5
Commit 613e91e85c (2024-09-06 18:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 32 × AMD Ryzen 9 5950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver3)
Threads: 32 default, 0 interactive, 16 GC (on 32 virtual cores)
Environment:
  JULIA_NUM_THREADS = 32

julia> using Pkg; pkg"status"
Status `~/.julia/environments/v1.10/Project.toml`
  [35d6a980] ColorSchemes v3.26.0
  [8f4d0f93] Conda v1.10.2
  [a93c6f00] DataFrames v1.6.1
  [31c24e10] Distributions v0.25.111
  [f6369f11] ForwardDiff v0.10.36
  [28b8d3ca] GR v0.73.7
  [7073ff75] IJulia v1.25.0
  [b6b21f68] Ipopt v1.6.6
  [4076af6c] JuMP v1.23.1
  [2fda8390] LsqFit v0.15.0
  [eff96d63] Measurements v2.11.0
  [961ee093] ModelingToolkit v9.39.1
  [7f7a1694] Optimization v3.28.0
  [3e6eede4] OptimizationBBO v0.3.0
  [36348300] OptimizationOptimJL v0.3.2
  [58dd65bb] Plotly v0.4.1
  [a03496cd] PlotlyBase v0.8.19
  [f0f68f2c] PlotlyJS v0.18.14
  [f2990250] PlotlyKaleido v2.2.5
  [91a5bcdd] Plots v1.40.8
  [92933f4c] ProgressMeter v1.10.2
  [274fc56d] PythonPlot v1.0.5
  [276daf66] SpecialFunctions v2.4.0
  [2913bbd2] StatsBase v0.34.3
  [1986cc42] Unitful v1.21.0
```

**Comment by LebedevRI** [comment] 2024-09-11 22:12
As per https://github.com/JuliaStats/Distributions.jl/blob/b219803a0d03a7c75d7aef7c0bab6cd0d79997dc/src/univariate/continuous/inversegaussian.jl#L153,
i'm guessing this is being used:
https://github.com/JuliaStats/Distributions.jl/blob/b219803a0d03a7c75d7aef7c0bab6cd0d79997dc/src/quantilealgs.jl#L44-L67
... and it isn't actually **guaranteed** to converge given real-world floating-point numbers? (`tol` too small?)

**Comment by devmotion** [comment] 2024-09-11 22:17
This seems to be a duplicate of https://github.com/JuliaStats/Distributions.jl/issues/1571, so please add comments to that issue 🙂

**Closed by devmotion** 2024-09-11 22:17 UTC
